//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANs
    {
        public string PAN { get; set; }
        public string MaskedPAN { get; set; }
    }
}
